AppResources.de.resx
AppResources.resx

Created by @chocolateflight and @moritzbabl
https://www.youtube.com/watch?v=8Pd7WqChX3A

Added Complete German Translation, Corrected Spelling Mistakes (English)

---

Strings/AppResources.Designer.cs
Strings/AppResources.de.resx
Strings/AppResources.es.resx
Strings/AppResources.fr.resx
Strings/AppResources.ms.resx
Strings/AppResources.pt.resx
Strings/AppResources.resx

FAA changed the definition, so we're changing it too: https://www.faa.gov/about/initiatives/notam/what_is_a_notam

Updating NOTAM and translations

---

Strings/AppResources.Designer.cs
Strings/AppResources.resx

- Trying again to merge the jet bridge strings

Jetbridge strings take deux

---

Strings/AppResources.he.resx

It's a given that RTL is causing some issues. As a result, I have removed any translation that causes problems with out-of-place parentheses, brackets, and words. Consequently, many Strings are still in English. However, Cameron and I are working on this—the first task is to get RTL to work properly in-app, followed by support for multi-font Strings.

Hebrew Translation (Strings/AppResources.resx only)

---

Strings/AppResources.zh.resx

This is temporary until we correctly support better line breaking in the app

Added line breaks to Simplified Chinese long-running sentences

---

Strings/AppResources.pt.resx

Updated Portuguese translations strings.

Portuguese translation update

---

Strings/AppResources.Designer.cs
Strings/AppResources.fr.resx
Strings/AppResources.resx

- Added ground service message when conditions are not met

Adding ground services msg

---

Strings/AppResources.Designer.cs
Strings/AppResources.bg.resx
Strings/AppResources.de.resx
Strings/AppResources.es.resx
Strings/AppResources.fr.resx
Strings/AppResources.he.resx
Strings/AppResources.ms.resx
Strings/AppResources.pt.resx
Strings/AppResources.resx
Strings/AppResources.zh.resx

Legacy Warning

---

Strings/AppResources.Designer.cs
Strings/AppResources.fr.resx
Strings/AppResources.resx

Proximity warning

---

Strings/AppResources.Designer.cs
Strings/AppResources.fr.resx
Strings/AppResources.resx

Sub message

---

Strings/AppResources.pt.resx

Made some typos corrections on translation, also added translated proximity warning.

Portuguese typos correction and added proximity warning translation

---

Strings/AppResources.zh.resx

Removed a bunch of manual line breakings

Removed line breaking

---

Strings/AppResources.hu.resx

Adding hungarian to only AppResources

23.2 Hungarian Fixes

---

OfficialTutorials/GettingStarted.json

Translating failure messages

---

Strings/AppResources.zh.resx

Also tweaked IF Pro ads translation formatting

Translate new strings

---

OfficialTutorials/GettingStarted.json
OfficialTutorials/SpaceShuttle.json
Strings/AppResources.de.resx

Added translations for missions and strings, streamlined error messages, improved AI translations based on their in-game context, fixed Sie/Du problems

Improved AI translations for German and added translations for new strings

---

Strings/AppResources.pt.resx

Translated new strings for 24.2 and corrected some olds strings.

Update to Portuguese translation

---

Strings/AppResources.bg.resx
Strings/AppResources.resx

- [Bulgarian] Added new strings
- [Bulgarian] Fixed grammatical case-related issues in some words
- [English] Fixed minor typo in one of the latest strings

New Strings

---

Strings/AppResources.bg.resx

- [Bulgarian] Added latest 2 strings (Main Menu)

24.4 Strings

---

Strings/AppResources.pt.resx

Updated the strings to new version (24.4)

New 24.4 Portuguese Strings

---

Tips/Tips.json

Additions were from Line 30 and below.

 New English ones added
